In [ ]:
import pandas as pd

In [ ]:
from google.colab import files
uploaded_file = files.upload()

Saving NetflixOriginals.csv to NetflixOriginals.csv

In [ ]:
import io
df1 = pd.read_csv(io.BytesIO(uploaded_file["NetflixOriginals.csv"]),encoding = "ISO-8859-1")

In [ ]:
#reading shape of dataset
df1.shape

(584, 6)

In [ ]:
#reading first 10 heads
df1.head(10)

,Title,Genre,Premiere,Runtime,IMDB Score,Language
0,Enter the Anime,Documentary,"August 5, 2019",58,2.5,English/Japanese
1,Dark Forces,Thriller,"August 21, 2020",81,2.6,Spanish
2,The App,Science fiction/Drama,"December 26, 2019",79,2.6,Italian
3,The Open House,Horror thriller,"January 19, 2018",94,3.2,English
4,Kaali Khuhi,Mystery,"October 30, 2020",90,3.4,Hindi
5,Drive,Action,"November 1, 2019",147,3.5,Hindi
6,Leyla Everlasting,Comedy,"December 4, 2020",112,3.7,Turkish
7,The Last Days of American Crime,Heist film/Thriller,"June 5, 2020",149,3.7,English
8,Paradox,Musical/Western/Fantasy,"March 23, 2018",73,3.9,English
9,Sardar Ka Grandson,Comedy,"May 18, 2021",139,4.1,Hindi

In [ ]:
#printting column names
df1.columns

Index(['Title', 'Genre', 'Premiere', 'Runtime', 'IMDB Score', 'Language'], dtype='object')

In [ ]:
#description of database......stattistical summary
df1.describe()

          Runtime  IMDB Score
count  584.000000  584.000000
mean    93.577055    6.271747
std     27.761683    0.979256
min      4.000000    2.500000
25%     86.000000    5.700000
50%     97.000000    6.350000
75%    108.000000    7.000000
max    209.000000    9.000000

In [ ]:
#printing information
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 584 entries, 0 to 583
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Title       584 non-null    object
 1   Genre       584 non-null    object
 2   Premiere    584 non-null    object
 3   Runtime     584 non-null    int64
 4   IMDB Score  584 non-null    float64
 5   Language    584 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 27.5+ KB

In [ ]:
#checking for null values
df1["Title"].isnull().sum()

0

In [ ]:
#checking for null values
df1["Title"].notnull().sum()

584

In [ ]:
#printing count of top scored IMDB movies
df1[df1["IMDB Score"] > 8].count()

Title         16
Genre         16
Premiere      16
Runtime       16
IMDB Score    16
Language      16
dtype: int64

In [ ]:
#printing lowest rated movies

t1 = df1[df1["IMDB Score"] < 5]

In [ ]:
t1

,Title,Genre,Premiere,Runtime,IMDB Score,Language
0,Enter the Anime,Documentary,"August 5, 2019",58,2.5,English/Japanese
1,Dark Forces,Thriller,"August 21, 2020",81,2.6,Spanish
2,The App,Science fiction/Drama,"December 26, 2019",79,2.6,Italian
3,The Open House,Horror thriller,"January 19, 2018",94,3.2,English
4,Kaali Khuhi,Mystery,"October 30, 2020",90,3.4,Hindi
5,Drive,Action,"November 1, 2019",147,3.5,Hindi
6,Leyla Everlasting,Comedy,"December 4, 2020",112,3.7,Turkish
7,The Last Days of American Crime,Heist film/Thriller,"June 5, 2020",149,3.7,English
8,Paradox,Musical/Western/Fantasy,"March 23, 2018",73,3.9,English
9,Sardar Ka Grandson,Comedy,"May 18, 2021",139,4.1,Hindi
10,Searching for Sheela,Documentary,"April 22, 2021",58,4.1,English
11,The Call,Drama,"November 27, 2020",112,4.1,Korean
12,Whipped,Romantic comedy,"September 18, 2020",97,4.1,Indonesian
13,All Because of You,Action comedy,"October 1, 2020",101,4.2,Malay
14,Mercy,Thriller,"November 22, 2016",90,4.2,English
15,After the Raid,Documentary,"December 19, 2019",25,4.3,Spanish
16,Ghost Stories,Horror anthology,"January 1, 2020",144,4.3,Hindi
17,The Last Thing He Wanted,Political thriller,"February 21, 2020",115,4.3,English
18,What Happened to Mr. Cha?,Comedy,"January 1, 2021",102,4.3,Korean
19,Death Note,Horror thriller,"August 25, 2017",100,4.4,English
20,"Hello Privilege. It's Me, Chelsea",Documentary,"September 13, 2019",64,4.4,English
21,Secret Obsession,Thriller,"July 18, 2019",97,4.4,English
22,Sextuplets,Comedy,"August 16, 2019",99,4.4,English
23,The Girl on the Train,Thriller,"February 26, 2021",120,4.4,Hindi
24,Thunder Force,Superhero-Comedy,"April 9, 2021",105,4.4,English
25,Fatal Affair,Thriller,"July 16, 2020",89,4.5,English
26,Just Say Yes,Romantic comedy,"April 2, 2021",97,4.5,Dutch
27,Seriously Single,Comedy,"July 31, 2020",107,4.5,English
28,The Misadventures of Hedi and Cokeman,Comedy,"February 10, 2021",99,4.5,French
29,5 Star Christmas,Comedy,"December 7, 2018",95,4.6,Italian
30,After Maria,Documentary,"May 24, 2019",37,4.6,English/Spanish
31,I Am the Pretty Thing That Lives in the House,Horror,"October 28, 2016",89,4.6,English
32,Paris Is Us,Romance drama,"February 22, 2019",83,4.6,French
33,Porta dos Fundos: The First Temptation of Christ,Comedy,"December 3, 2019",46,4.6,Portuguese
34,Rattlesnake,Horror,"October 25, 2019",85,4.6,English
35,The Players,Comedy,"July 15, 2020",88,4.6,Italian
36,We Are One,Documentary,"July 14, 2020",86,4.6,French
37,Finding Agnes,Drama,"November 30, 2020",105,4.7,Filipino
38,IO,Science fiction/Drama,"January 18, 2019",95,4.7,English
39,Sentinelle,Action,"March 5, 2021",80,4.7,French
40,Sol Levante,Anime / Short,"April 2, 2020",4,4.7,English
41,The Binding,Drama,"October 2, 2020",93,4.7,Italian
42,We Can Be Heroes,Superhero,"December 25, 2020",100,4.7,English
43,Christmas Crossfire,Thriller,"December 4, 2020",106,4.8,German
44,Coin Heist,Heist,"January 6, 2017",97,4.8,English
45,Mrs. Serial Killer,Thriller,"May 1, 2020",106,4.8,Hindi
46,Nobody Sleeps in the Woods Tonight,Horror,"October 28, 2020",103,4.8,Polish
47,Take the 10,Comedy,"January 20, 2017",80,4.8,English
48,The Main Event,Comedy,"April 10, 2020",101,4.8,English
49,The Ridiculous 6,Western,"December 11, 2015",119,4.8,English
50,Earth and Blood,Action,"April 17, 2020",80,4.9,French
51,Fearless,Animation/Superhero,"August 14, 2020",89,4.9,English
52,Holiday Rush,Family film,"November 28, 2019",94,4.9,English
53,The Day of the Lord,Drama,"October 30, 2020",93,4.9,Spanish

In [ ]:
t1.count()

Title         54
Genre         54
Premiere      54
Runtime       54
IMDB Score    54
Language      54
dtype: int64

In [ ]:
df1.duplicated

<bound method DataFrame.duplicated of                                            Title                  Genre  \
0                                Enter the Anime            Documentary
1                                    Dark Forces               Thriller
2                                        The App  Science fiction/Drama
3                                 The Open House        Horror thriller
4                                    Kaali Khuhi                Mystery
..                                           ...                    ...
579        Taylor Swift: Reputation Stadium Tour           Concert Film
580  Winter on Fire: Ukraine's Fight for Freedom            Documentary
581                      Springsteen on Broadway           One-man show
582    Emicida: AmarElo - It's All For Yesterday            Documentary
583     David Attenborough: A Life on Our Planet            Documentary

              Premiere  Runtime  IMDB Score                  Language
0       August 5, 2019       58         2.5          English/Japanese
1      August 21, 2020       81         2.6                   Spanish
2    December 26, 2019       79         2.6                   Italian
3     January 19, 2018       94         3.2                   English
4     October 30, 2020       90         3.4                     Hindi
..                 ...      ...         ...                       ...
579  December 31, 2018      125         8.4                   English
580    October 9, 2015       91         8.4  English/Ukranian/Russian
581  December 16, 2018      153         8.5                   English
582   December 8, 2020       89         8.6                Portuguese
583    October 4, 2020       83         9.0                   English

[584 rows x 6 columns]>

In [ ]:
#finding hindi movies in db 
t2 = df1[df1["Language"]=="Hindi"]

In [ ]:
t2.count()

Title         33
Genre         33
Premiere      33
Runtime       33
IMDB Score    33
Language      33
dtype: int64

In [ ]:
t2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 33 entries, 4 to 551
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Title       33 non-null     object
 1   Genre       33 non-null     object
 2   Premiere    33 non-null     object
 3   Runtime     33 non-null     int64
 4   IMDB Score  33 non-null     float64
 5   Language    33 non-null     object
dtypes: float64(1), int64(1), object(4)
memory usage: 1.8+ KB

In [ ]:
t3 = df1["Language"].unique()

In [ ]:
t3

array(['English/Japanese', 'Spanish', 'Italian', 'English', 'Hindi',
       'Turkish', 'Korean', 'Indonesian', 'Malay', 'Dutch', 'French',
       'English/Spanish', 'Portuguese', 'Filipino', 'German', 'Polish',
       'Norwegian', 'Marathi', 'Thai', 'Swedish', 'Japanese',
       'Spanish/Basque', 'Spanish/Catalan', 'English/Swedish',
       'English/Taiwanese/Mandarin', 'Thia/English', 'English/Mandarin',
       'Georgian', 'Bengali', 'Khmer/English/French', 'English/Hindi',
       'Tamil', 'Spanish/English', 'English/Korean', 'English/Arabic',
       'English/Russian', 'English/Akan', 'English/Ukranian/Russian'],
      dtype=object)

In [ ]:
df1[df1["Language"]=="English"].count()

Title         401
Genre         401
Premiere      401
Runtime       401
IMDB Score    401
Language      401
dtype: int64

In [ ]:
df1[df1["Language"]=="English"].nunique()

Title         401
Genre         101
Premiere      307
Runtime       114
IMDB Score     49
Language        1
dtype: int64

In [ ]:
for i in t3:
  print("language is : ",i)
  print(df1[df1["Language"]==i].count())

language is :  English/Japanese
Title         2
Genre         2
Premiere      2
Runtime       2
IMDB Score    2
Language      2
dtype: int64
language is :  Spanish
Title         31
Genre         31
Premiere      31
Runtime       31
IMDB Score    31
Language      31
dtype: int64
language is :  Italian
Title         14
Genre         14
Premiere      14
Runtime       14
IMDB Score    14
Language      14
dtype: int64
language is :  English
Title         401
Genre         401
Premiere      401
Runtime       401
IMDB Score    401
Language      401
dtype: int64
language is :  Hindi
Title         33
Genre         33
Premiere      33
Runtime       33
IMDB Score    33
Language      33
dtype: int64
language is :  Turkish
Title         5
Genre         5
Premiere      5
Runtime       5
IMDB Score    5
Language      5
dtype: int64
language is :  Korean
Title         6
Genre         6
Premiere      6
Runtime       6
IMDB Score    6
Language      6
dtype: int64
language is :  Indonesian
Title         9
Genre         9
Premiere      9
Runtime       9
IMDB Score    9
Language      9
dtype: int64
language is :  Malay
Title         1
Genre         1
Premiere      1
Runtime       1
IMDB Score    1
Language      1
dtype: int64
language is :  Dutch
Title         3
Genre         3
Premiere      3
Runtime       3
IMDB Score    3
Language      3
dtype: int64
language is :  French
Title         20
Genre         20
Premiere      20
Runtime       20
IMDB Score    20
Language      20
dtype: int64
language is :  English/Spanish
Title         5
Genre         5
Premiere      5
Runtime       5
IMDB Score    5
Language      5
dtype: int64
language is :  Portuguese
Title         12
Genre         12
Premiere      12
Runtime       12
IMDB Score    12
Language      12
dtype: int64
language is :  Filipino
Title         2
Genre         2
Premiere      2
Runtime       2
IMDB Score    2
Language      2
dtype: int64
language is :  German
Title         5
Genre         5
Premiere      5
Runtime       5
IMDB Score    5
Language      5
dtype: int64
language is :  Polish
Title         3
Genre         3
Premiere      3
Runtime       3
IMDB Score    3
Language      3
dtype: int64
language is :  Norwegian
Title         1
Genre         1
Premiere      1
Runtime       1
IMDB Score    1
Language      1
dtype: int64
language is :  Marathi
Title         3
Genre         3
Premiere      3
Runtime       3
IMDB Score    3
Language      3
dtype: int64
language is :  Thai
Title         2
Genre         2
Premiere      2
Runtime       2
IMDB Score    2
Language      2
dtype: int64
language is :  Swedish
Title         1
Genre         1
Premiere      1
Runtime       1
IMDB Score    1
Language      1
dtype: int64
language is :  Japanese
Title         6
Genre         6
Premiere      6
Runtime       6
IMDB Score    6
Language      6
dtype: int64
language is :  Spanish/Basque
Title         1
Genre         1
Premiere      1
Runtime       1
IMDB Score    1
Language      1
dtype: int64
language is :  Spanish/Catalan
Title         1
Genre         1
Premiere      1
Runtime       1
IMDB Score    1
Language      1
dtype: int64
language is :  English/Swedish
Title         1
Genre         1
Premiere      1
Runtime       1
IMDB Score    1
Language      1
dtype: int64
language is :  English/Taiwanese/Mandarin
Title         1
Genre         1
Premiere      1
Runtime       1
IMDB Score    1
Language      1
dtype: int64
language is :  Thia/English
Title         1
Genre         1
Premiere      1
Runtime       1
IMDB Score    1
Language      1
dtype: int64
language is :  English/Mandarin
Title         2
Genre         2
Premiere      2
Runtime       2
IMDB Score    2
Language      2
dtype: int64
language is :  Georgian
Title         1
Genre         1
Premiere      1
Runtime       1
IMDB Score    1
Language      1
dtype: int64
language is :  Bengali
Title         1
Genre         1
Premiere      1
Runtime       1
IMDB Score    1
Language      1
dtype: int64
language is :  Khmer/English/French
Title         1
Genre         1
Premiere      1
Runtime       1
IMDB Score    1
Language      1
dtype: int64
language is :  English/Hindi
Title         2
Genre         2
Premiere      2
Runtime       2
IMDB Score    2
Language      2
dtype: int64
language is :  Tamil
Title         1
Genre         1
Premiere      1
Runtime       1
IMDB Score    1
Language      1
dtype: int64
language is :  Spanish/English
Title         1
Genre         1
Premiere      1
Runtime       1
IMDB Score    1
Language      1
dtype: int64
language is :  English/Korean
Title         1
Genre         1
Premiere      1
Runtime       1
IMDB Score    1
Language      1
dtype: int64
language is :  English/Arabic
Title         1
Genre         1
Premiere      1
Runtime       1
IMDB Score    1
Language      1
dtype: int64
language is :  English/Russian
Title         1
Genre         1
Premiere      1
Runtime       1
IMDB Score    1
Language      1
dtype: int64
language is :  English/Akan
Title         1
Genre         1
Premiere      1
Runtime       1
IMDB Score    1
Language      1
dtype: int64
language is :  English/Ukranian/Russian
Title         1
Genre         1
Premiere      1
Runtime       1
IMDB Score    1
Language      1
dtype: int64

NameError: ignored